Improved PKGBUILD
Fixed #46.

diff --git a/build/linux/PKGBUILD b/build/linux/PKGBUILD
--- a/build/linux/PKGBUILD
+++ b/build/linux/PKGBUILD
@@ -1,6 +1,6 @@
 # Maintainer: Spacingbat3 (https://github.com/spacingbat3)
 pkgname=webcord-git
-pkgver=v1.4.0_pre1.r127.901707b
+pkgver=v1.4.0_pre1.r132.84fdc0d
 pkgrel=1
 pkgdesc="A Discord client based on the Electron engine."
 arch=("any")
@@ -33,25 +33,51 @@ build() {
         printf "\r%-${1}s" "${2}"
     }
     _icons=("${srcdir}/${pkgname%-git}/icons/app.png"
-            "${srcdir}/${pkgname%-git}/extra/iconThemes/Papirus/webcord.svg")
+            "${srcdir}/extra/iconThemes/Papirus/webcord.svg")
     _terminal() {
         printf "#!/bin/bash\nelectron /usr/lib/${pkgname%-git}.asar\nexit \$?">"$1"
     }
     cd "${srcdir}/${pkgname%-git}"
-    [[ -f docs/COPYING ]] && mv docs/COPYING ../ && rm -R docs
-    [[ -f build ]] && rm -R build
-    for _target in "../${pkgname%-git}.asar" "../iconThemes" "icons/app.ico" "icons/app.icns"; do
+
+    # Clean workspace and remove unnecesary files:
+
+    _PACKAGE_IGNORE=("../${pkgname%-git}.asar" "../iconThemes" "icons/app.ico"
+                    "icons/app.icns" "src/js/configForge.js" "src/ts/configForge.ts"
+                    ".gitignore" "package-lock.json" ".eslintrc.json" "../docs" "build"
+                    ".github")
+
+    for _target in "${_PACKAGE_IGNORE[@]}"; do
         if [[ -f "${_target}" ]]; then
             rm "${_target}"
         elif [[ -d "${_target}" ]]; then
             rm -R "${_target}"
         fi
     done
-    npx asar pack . ../${pkgname%-git}.asar || { echo "Failed to package to ASAR!"; exit 1;}
+
+    # Move documentation files, license and 'extra' files outside sources
+
+    [[ -f docs/COPYING ]] && mv docs/COPYING ../COPYING
+    [[ -d docs ]] && mv docs ../docs
+    [[ -d extra ]] && mv extra ../extra
+
+    # Temporarily move '.git' outside the sources (if exists)
+
+    [[ -d .git ]] && mv .git ../git-data
+
+    # Build, package and generate simple executable script
+    # that initializes Electron:
+
+    npm run build
+    npx asar pack . ../${pkgname%-git}.asar || { echo "Failed to package to ASAR!"; exit 1; }
     _terminal "../${pkgname%-git}.sh"
+
+    [[ -d ../git-data ]] && mv ../git-data ./git
+
+    # Generate icons:
+
     mkdir "../iconThemes"
     cd "../iconThemes"
-    _sizes_2=(128 96 64 48 32 24 22 18 16 8)
+    _sizes_2=(128 96 64 48 32 24 22 18 16 8) # Papirus supported sizes
     _sizes_1=(512 256 ${_sizes_2[@]})
     _i=1
     mkdir "themeId-${_i}"
@@ -82,14 +108,26 @@ build() {
 
 package() {
     cd "${srcdir}"
+
+    # Neccesary files – application data, license etc.
+
     install -Dm755 "${pkgname%-git}.asar" "${pkgdir}/usr/lib/${pkgname%-git}.asar"
+    install -Dm755 "${pkgname%-git}.sh" "${pkgdir}/usr/bin/${pkgname%-git}"
+    install -Dm755 "${pkgname%-git}.desktop" "${pkgdir}/usr/share/applications/${pkgname%-git}.desktop"
     install -Dm644 "COPYING" "${pkgdir}/usr/share/licenses/${pkgname%-git}/COPYING"
+
+    # Application icons – Default + Papirus (extra)
+
     install -dm755 "${pkgdir}/usr/share/icons"
     cp -R "iconThemes/themeId-1/" "${pkgdir}/usr/share/icons/hicolor"
     cp -R "iconThemes/themeId-2/" "${pkgdir}/usr/share/icons/Papirus"
     cp -R "iconThemes/themeId-2/" "${pkgdir}/usr/share/icons/Papirus-Dark"
     cp -R "iconThemes/themeId-2/" "${pkgdir}/usr/share/icons/ePapirus"
     chmod 0644 "${pkgdir}/usr/share/icons"/*/*/*/"${pkgname%-git}."*
-    install -Dm755 "${pkgname%-git}.desktop" "${pkgdir}/usr/share/applications/${pkgname%-git}.desktop"   
-    install -Dm755 "${pkgname%-git}.sh" "${pkgdir}/usr/bin/${pkgname%-git}"
+
+    # Documentation
+
+    install -dm755 "${pkgdir}/usr/share/docs"
+    cp -R "docs/" "${pkgdir}/usr/share/docs/${pkgname%-git}/"
+    chmod 0644 "${pkgdir}/usr/share/docs/${pkgname%-git}/"
 }
